- name: Setup and Deploy Private VM
  hosts: private_vm
  become: true
  gather_facts: false
  tasks:
    - name: Install Python 3
      ansible.builtin.apt:
        name: python3
        state: present
        update_cache: true

    - name: Download K3s installation script for private_vm
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'
      become: true

    - name: Install K3s (Kubernetes) for public_vm
      ansible.builtin.command: /bin/bash /tmp/k3s_install.sh
      become: true
      args:
        creates: /usr/local/bin/k3s

    - name: Check if K3s service is running
      ansible.builtin.systemd:
        name: k3s
        state: started
      register: k3s_status
      changed_when: false
      failed_when: k3s_status.status.State != 'running'

    - name: Copy MariaDB deployment file
      ansible.builtin.copy:
        src: mariadb-deployment.yaml
        dest: /tmp/mariadb-deployment.yaml
        mode: '0644'

    - name: Copy MariaDB service file
      ansible.builtin.copy:
        src: mariadb-service.yaml
        dest: /tmp/mariadb-service.yaml
        mode: '0644'

    - name: Apply the MariaDB deployment
      kubernetes.core.k8s:
        state: present
        namespace: default
        kubeconfig: /Users/obarrientos/kubecfg_prodigiesai
        definition: "{{ lookup('file', 'mariadb-deployment.yaml') }}"

    - name: Apply the MariaDB service
      kubernetes.core.k8s:
        state: present
        namespace: default
        kubeconfig: /Users/obarrientos/kubecfg_prodigiesai
        definition: "{{ lookup('file', 'mariadb-service.yaml') }}"
